import { Inter } from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/system";
import { SummaryProvider } from '../app/SummaryContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Discharge Summary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="relative" lang="en">
      <body className={inter.className}>
      {/* <NextUIProvider> */}
      <SummaryProvider>
          {children}
        {/* </NextUIProvider> */}
        </SummaryProvider>
        </body>
    </html>
  );
}
